### ISSUE TITLE
Deprecation warning: Support for defaultProps will be removed from function components

### ISSUE THREAD

**Issue by sbolel** [aquia-inc/template-vite-react#23]
# Bug Report Description

Running the application shows the following warning in the javascript console:

```
react-dom.development.js:86 Warning: SubmitButton: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at SubmitButton (http://localhost:5173/src/components/forms/SubmitButton.tsx:20:29)
    at form
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at Grid2 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:2717:24)
    at SignInForm (http://localhost:5173/src/views/SignIn/SignIn.tsx:69:102)
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at Box3 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:533:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at Box3 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:533:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at Box3 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:533:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at div
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at Box3 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:533:19)
    at http://localhost:5173/node_modules/.vite/deps/chunk-OQXAPCKX.js?v=d6448a19:1701:50
    at SignIn (http://localhost:5173/src/views/SignIn/SignIn.tsx:175:29)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3653:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3613:5)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3653:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3613:5)
    at Outlet (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:4024:26)
    at DialogProvider (http://localhost:5173/src/hooks/useDialog.tsx:21:27)
    at AlertProvider (http://localhost:5173/src/hooks/useAlert.tsx:27:33)
    at AuthProvider (http://localhost:5173/src/store/auth/AuthProvider.tsx:27:29)
    at RtlProvider (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:910:5)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:859:5)
    at ThemeProvider2 (http://localhost:5173/node_modules/.vite/deps/chunk-LILNPRW7.js?v=d6448a19:949:5)
    at ThemeProvider (http://localhost:5173/node_modules/.vite/deps/chunk-2NI66VHR.js?v=d6448a19:296:12)
    at Root
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3653:5)
    at RenderErrorBoundary (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:3613:5)
    at DataRoutes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:4766:5)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:4031:15)
    at RouterProvider (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=6f24415e:4583:5)
```

## How can this issue be reproduced?

- start the application with `yarn dev`
- navigate to the app at http://localhost:5173 and open the developer console
- observe the deprecation warning

## What is the expected behavior?

- there is no warning in the dev console

## What is the motivation / use case for changing the behavior?

- make the application ready for future versions of react

## Please tell us about your environment:

- n/a

## Other information:

- n/a

**Comment by sbolel** [comment]
@ATNoblis FYI you will also run into this issue when using the template. We'll need to figure out where all the occurrences of this are so that we can fix it systematically.
